services:
  zookeeper:
    image: zookeeper:3.9
    container_name: helloapp-zookeeper
    restart: unless-stopped
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: helloapp-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092

  app:
    build: .
    container_name: helloapp-app
    depends_on:
      - kafka
    ports:
      - 8086:8086
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/studentdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Chitti@01
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: 'true'

volumes:
  mysql-data:
